version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app 
    command: node index.js
      
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: ejemplo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: